GET http://localhost:3003/endereco/05424150

###
post https://exer-serv-backend.herokuapp.com/user/05424150

###
GET https://exer-serv-backend.herokuapp.com/list
###
post http://localhost:3003/user/05424150

###
GET http://localhost:3003/list
